name: myinternplus
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  mobile_scanner: ^7.1.3
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  #  flutter_local_notifications: ^16.3.0
  dio: ^5.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  package_info_plus: ^8.3.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - "assets/images/InternLogo.png"
    - "assets/images/InternLogoExpand.png"
    - "assets/images/Mascot1.png"
    - "assets/images/Mascot2.png"
    - "assets/images/Mascot3.png"
    - "assets/images/Mascot4.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/InternLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/InternLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/InternLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/InternLogo.png"