name: myinternplus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Architecture
  provider: ^6.1.1

  # Networking
  http: ^1.1.0
  dio: ^5.0.0

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  path_provider: ^2.1.1
  package_info_plus: ^8.3.1

  # Media & Assets
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.0
  gal: ^2.3.0

  # UI Components
  fl_chart: ^1.1.1
  fluttertoast: ^9.0.0

  # QR & Scanner
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0

  # Notifications & Timezone
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # Others
  share_plus: ^7.2.1
  multicast_dns: ^0.3.2
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - "assets/images/InternLogo.png"
    - "assets/images/InternLogoExpand.png"
    - "assets/images/Mascot1.png"
    - "assets/images/Mascot2.png"
    - "assets/images/Mascot3.png"
    - "assets/images/Mascot4.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/InternLogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/InternLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/InternLogo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/InternLogo.png"